### ISSUE TITLE
Support for Subscriber Attributes

### ISSUE THREAD

**Issue by Spone** [fishbrain/tarpon#15]
I'd like to be able to specify Subscriber Attributes when calling 

```rb
Tarpon::Client
    .subscriber(user.revenuecat_id)
    .get_or_create
```

See docs: https://www.revenuecat.com/reference/subscribers#the-subscriber-attribute-object

What do you think? Would you be open for a PR?

**Comment by igorbelo** [comment]
Hi @Spone,

From the docs you referenced it doesn't seem possible to pass subscriber attributes to that endpoint.
Am I missing something?

**Comment by Spone** [comment]
Hi @igorbelo, sorry about that, you're totally right. There is a separate endpoint to update Subscriber Attributes: https://www.revenuecat.com/reference/update-subscriber-attributes

I don't think it's supported by Tarpon (yet?) : https://github.com/fishbrain/tarpon/blob/master/lib/tarpon/request/subscriber.rb
Would you consider supporting it?

**Comment by igorbelo** [comment]
Yes, for sure.
Feel free to open a Pull Request providing that feature.

**Comment by Spone** [comment]
Awesome! I'll be pairing up with my coworker @MohamedBng on this!
